name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Checkout Yap
        uses: actions/checkout@v4

      - name: Node.js Ortamını Kur
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Bağımlılıkları Yükle
        run: npm ci

      - name: Next.js Sitesini Build Et
        run: npm run build

      - name: Artifact'ı Yükle
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: GitHub Pages'a Dağıt
        id: deployment
        uses: actions/deploy-pages@v4
