name: Build and Deploy (GitHub Pages)

on:
  push:
    branches:
      - main
      - yeni-ozellik
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAGES: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --force

      - name: Build and export static site
        env:
          GITHUB_PAGES: 'true'
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -f out/
          git commit --allow-empty -m "Deploy to GitHub Pages [skip ci]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kadirayana/ReactorDesign.git
          git push -f origin HEAD:gh-pages
