name: Build and Deploy (GitHub Pages)

on:
  push:
    branches:
      - main
      - yeni-ozellik
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAGES: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --force

      - name: Build and export static site
        env:
          GITHUB_PAGES: 'true'
        run: |
          npm run build
          if [ ! -d out ]; then
            echo "out/ not found, checking for .next/static/..."
            if [ -d .next ]; then
              mkdir -p out
              cp -r .next/static out/ || true
            fi
          fi

      - name: Check build output
        run: |
          echo "Contents of workspace:"
          ls -la
          echo ""
          if [ -d out ]; then
            echo "✓ out/ exists"
            find out -type f | head -20
          else
            echo "✗ out/ NOT found - build may have failed"
            ls -la .next 2>/dev/null | head -10 || echo "No .next/ either"
          fi

      - name: Deploy to GitHub Pages
        run: |
          if [ ! -d out ] || [ -z "$(ls -A out 2>/dev/null)" ]; then
            echo "ERROR: out/ directory is empty or missing"
            exit 1
          fi
          
          mkdir -p deploy
          cp -r out/* deploy/ || exit 1
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          # Try GH_TOKEN first (personal access token), fallback to GITHUB_TOKEN
          TOKEN="${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/kadirayana/ReactorDesign.git
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r deploy/* .
          rm -rf deploy
          git add .
          git commit -m "Deploy to GitHub Pages [skip ci]"
          git push -f origin gh-pages
